package gui;

import java.awt.CardLayout;


public class TampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambarComboBox
     */
    public TampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPanel = new javax.swing.JPanel();
        comboLB = new javax.swing.JLabel();
        optionCB = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        fisikaLB = new javax.swing.JLabel();
        biologiLB = new javax.swing.JLabel();
        kimiaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tampil Gambar (Combo Box)");

        comboPanel.setBackground(new java.awt.Color(255, 255, 102));

        comboLB.setBackground(new java.awt.Color(255, 255, 255));
        comboLB.setForeground(new java.awt.Color(0, 0, 0));
        comboLB.setText("Pilih Gambar");
        comboPanel.add(comboLB);

        optionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisika", "Biologi", "Kimia" }));
        optionCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optionCBItemStateChanged(evt);
            }
        });
        comboPanel.add(optionCB);

        getContentPane().add(comboPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        fisikaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fisikaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Fisika.jpg"))); // NOI18N
        fisikaLB.setToolTipText("null");
        imagePanel.add(fisikaLB, "Fisika");

        biologiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biologiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Biologi.jpg"))); // NOI18N
        biologiLB.setToolTipText("null");
        imagePanel.add(biologiLB, "Biologi");

        kimiaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kimiaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Kimia.jpg"))); // NOI18N
        kimiaLB.setToolTipText("null");
        imagePanel.add(kimiaLB, "Kimia");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optionCBItemStateChanged
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, String.valueOf(optionCB.getSelectedItem()));
    }//GEN-LAST:event_optionCBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biologiLB;
    private javax.swing.JLabel comboLB;
    private javax.swing.JPanel comboPanel;
    private javax.swing.JLabel fisikaLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel kimiaLB;
    private javax.swing.JComboBox<String> optionCB;
    // End of variables declaration//GEN-END:variables
}
