/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

public class TampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambarButton
     */
    public TampilGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        fisikaBT = new javax.swing.JButton();
        kimiaBT = new javax.swing.JButton();
        biologiBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        fisikaLB = new javax.swing.JLabel();
        biologiLB = new javax.swing.JLabel();
        kimiaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tampil Gambar (Button)");

        fisikaBT.setText("Fisika");
        fisikaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisikaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(fisikaBT);

        kimiaBT.setText("Kimia");
        kimiaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimiaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(kimiaBT);

        biologiBT.setText("Biologi");
        biologiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologiBTActionPerformed(evt);
            }
        });
        buttonPanel.add(biologiBT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        fisikaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Fisika.jpg"))); // NOI18N
        imagePanel.add(fisikaLB, "fisika");

        biologiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Biologi.jpg"))); // NOI18N
        imagePanel.add(biologiLB, "biologi");

        kimiaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Kimia.jpg"))); // NOI18N
        imagePanel.add(kimiaLB, "kimia");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fisikaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisikaBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "fisika");
    }//GEN-LAST:event_fisikaBTActionPerformed

    private void kimiaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimiaBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "kimia");
    }//GEN-LAST:event_kimiaBTActionPerformed

    private void biologiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologiBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "biologi");
    }//GEN-LAST:event_biologiBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biologiBT;
    private javax.swing.JLabel biologiLB;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton fisikaBT;
    private javax.swing.JLabel fisikaLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton kimiaBT;
    private javax.swing.JLabel kimiaLB;
    // End of variables declaration//GEN-END:variables
}
