package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

public class TampilGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambarButtonFullScreen
     */
    public TampilGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        fisikaBT = new javax.swing.JButton();
        biologiBT = new javax.swing.JButton();
        kimiaBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        fisikaLB = new javax.swing.JLabel();
        biologiLB = new javax.swing.JLabel();
        kimiaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tampil Gambar (Fullscreen)");
        setUndecorated(true);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0));

        fisikaBT.setBackground(new java.awt.Color(153, 0, 153));
        fisikaBT.setForeground(new java.awt.Color(0, 0, 0));
        fisikaBT.setText("Fisika");
        fisikaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisikaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(fisikaBT);

        biologiBT.setBackground(new java.awt.Color(102, 255, 102));
        biologiBT.setForeground(new java.awt.Color(0, 0, 0));
        biologiBT.setText("Biologi");
        biologiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologiBTActionPerformed(evt);
            }
        });
        buttonPanel.add(biologiBT);

        kimiaBT.setBackground(new java.awt.Color(255, 0, 255));
        kimiaBT.setForeground(new java.awt.Color(0, 0, 0));
        kimiaBT.setText("Kimia");
        kimiaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimiaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(kimiaBT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        fisikaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fisikaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Fisika.jpg"))); // NOI18N
        fisikaLB.setToolTipText("null");
        imagePanel.add(fisikaLB, "card1");

        biologiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biologiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Biologi.jpg"))); // NOI18N
        biologiLB.setToolTipText("null");
        imagePanel.add(biologiLB, "card2");

        kimiaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kimiaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Kimia.jpg"))); // NOI18N
        kimiaLB.setToolTipText("null");
        imagePanel.add(kimiaLB, "card3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fisikaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisikaBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "card1");
    }//GEN-LAST:event_fisikaBTActionPerformed

    private void biologiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologiBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "card2");
    }//GEN-LAST:event_biologiBTActionPerformed

    private void kimiaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimiaBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel,"card3");
    }//GEN-LAST:event_kimiaBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TampilGambarButtonFullScreen fullFrame = new TampilGambarButtonFullScreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biologiBT;
    private javax.swing.JLabel biologiLB;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton fisikaBT;
    private javax.swing.JLabel fisikaLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton kimiaBT;
    private javax.swing.JLabel kimiaLB;
    // End of variables declaration//GEN-END:variables
}
